print("Server Report")
print("Server: Running")
print("Backup: OK")
print("Disk Usage: 45% used")
print("Memory Usage: 2.4GB / 8GB")
print("Network Status: Online")
print("Latency: 12ms")
print("Critical Hotfix: Patch Applied")
